# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnlyMacController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'
  # Pods for OnlyMacController

  target 'OnlyMacControllerTests' do
    inherit! :search_paths
    pod 'CocoaAsyncSocket' 
    # Pods for testing
  end

  target 'OnlyMacControllerUITests' do
    # Pods for testing
    pod 'CocoaAsyncSocket' 
  end

end
